### ISSUE TITLE
How many Shards did you configure in the Stream?

### ISSUE THREAD

**Issue by IanMeyers** [thomas-schreiter/ingestion_benchmark#1]
Hello,

I don't see anywhere that you cite how many Shards you configured for this Kinesis Stream, so would be curious about this point.

Thanks!

Ian

**Comment by thomas-schreiter** [comment]
Hi Ian,

I played around with 1 to 4 shards. But that didn't change the throughput. So then I mostly used 1 shard to keep it simple.

(Sorry for the late response. I must have missed the notification.)

**Comment by ajmssc** [comment]
It's hard to imagine that your throughput would remain the same with more shards... Were you using the KPL?

Did you partition your Kafka topics?

Because the two systems work very differently under the hood, I think you should have used cost as your input and looked at how much throughput per dollar you could get out of each system.

**Comment by IanMeyers** [comment]
I'm a Solution Architect with AWS specialising in Kinesis, and I'd be happy to help with addressing some of the constraints that this benchmark might have encountered. 

Specifically by using just a single producer and consumer, you weren't able to take best advantage of multiple Shards, which is the unit of scalability for Kinesis and in some ways is analogous to a Kafka broker. Your code uses a Pool to start producers and consumers. Your producers use a synchronous PutRecords API call, which will block the sending thread until completion, which isn't strictly required and will create a natural throttle. More importantly, your consumer is consuming messages serially from the ShardIterator. Instead of streaming through each record (`out = self.con.get_records(shard_it, limit=1)`, you should instead use a limit of `None` and then count the number of records returned from that single GetRecords API call. You can then run one consumer per Shard, and sum the returned message counts from each worker thread to determine a total Stream level throughput metric. This will scale up to the limit of the network card on the EC2 instance you are using, and because you have a combined producer and consumer workload in this benchmark will constitute an artificial bottleneck. It would be better to run separate machines for producers and consumers in either case. To completely remove the networking bottleneck, ensure that you have one consumer per shard per 2MB of network bandwidth (the read throughput limit per Shard) provided on the EC2 instance. A simple way to do this would be to run one machine per shard, with a single consumer running on that machine.

As @ajmssc indicated, the ultimate metric is cost per N messages. With Kinesis you get 1000 messages/second @ 1MB per Shard of ingest for $.015 (1.5 cents) USD per Hour. You are using 4 m3.large instances for Kafka, which cost $.146 / hour in EU West each, totalling $.584/hour. A direct comparison from a cost perspective would therefore be to run your ingestion benchmark with the above changes to the testing code to ensure network bottlenecks don't get in the way, but with **38 Shards**. Your ingestion benchmark showed 4 Kafka brokers maxing out at 30K messages/second, but 38 Shards will deliver 38K messages/second for the same cost without optimisation, provided that your producers and consumers can keep up. By using the message aggregation feature provided in the Kinesis Producer Library, with the message size used in your benchmark of ~ 100 Bytes, we'd be able to support producing 10,000 messages per Record, and get 30K messages/second from just ~ 3 Shards with a cost 12x lower than your Kafka infrastructure.

Please let me know if you'd be interested in collaborating on changes to this codebase and getting a test environment setup to demonstrate the performance that is possible with Kinesis.
